# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "get certificates"
  lane :get do
    get_certificates(development: true)         # invokes cert
    get_provisioning_profile(development: true)  # invokes sigh
  end

  desc "Description of what the lane does"
  lane :release do
    sync_code_signing(type: "adhoc")
    build_app(
      workspace: "crm.xcworkspace", 
      scheme: "hsbenhan", 
      output_directory: "./build", 
      silent: true,
      clean: true,
      output_name: "hsbenhanApp", 
      export_method: "ad-hoc"
    )
    upload_diawi
  end
  
  lane :upload_diawi do 
    diawi(
      token: "3rROTjnjBkkGulZelN8TSp72PeEEShXG4BNq2KuTii"
    )
  end
end
